name: Test Storybook with SmartUI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Create commit status
        env:
          PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
        run: |
          API_HOST=https://api.github.com
          OWNER=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)
          REPO=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          git checkout $GITHUB_HEAD_REF
          COMMIT_ID=$(git rev-parse HEAD)
          echo "Last commit ID of PR: $COMMIT_ID"
          REF=$GITHUB_SHA
          echo "Current Commit ID REF : $REF"
          GITHUB_URL=$API_HOST/repos/$GITHUB_REPOSITORY/statuses/$COMMIT_ID
          echo "GITHUB_URL: $GITHUB_URL"
          echo "GITHUB_URL=$GITHUB_URL" >> $GITHUB_ENV

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Install Lambda CLI
        run: npm install @lambdatest/smartui-storybook -g

      - name: Run Storybook
        run: npm run build-storybook

      - name: Give some time to start the Storybook server
        run: |
          echo "Start sleeping..."
          sleep 30  # Sleep for 30 seconds
          echo "Done sleeping."

      - name: Upload screenshots
        env:
          PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
        id: upload_screenshots
        run: |
          build_output=$(npx smartui storybook ./storybook-static --config .smartui.json)
          echo "$build_output"
          build_id=$(echo "$build_output" | grep -oP '(?<=Build ID:  )\S+')
          echo "BUILD_ID=$build_id" >> $GITHUB_ENV
          echo "::set-output name=build_id::$build_id"
        continue-on-error: true

      - name: Debug Build ID 1
        run: |
          echo "Build ID: ${{ steps.upload_screenshots.outputs.build_id }}"
          echo "Environment Build ID: $BUILD_ID"

      - name: Give some time to let the previous comparison finish
        run: |
          echo "Start sleeping..."
          sleep 30  # Sleep for 30 seconds
          echo "Done sleeping."
        if: always()

      - name: Create commit status
        env:
          PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN2 }}
        run: |
          API_HOST=https://api.github.com
          OWNER=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)
          REPO=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          git checkout $GITHUB_HEAD_REF
          COMMIT_ID=$(git rev-parse HEAD)
          echo "Last commit ID of PR: $COMMIT_ID"
          REF=$GITHUB_SHA
          echo "Current Commit ID REF : $REF"
          GITHUB_URL=$API_HOST/repos/$GITHUB_REPOSITORY/statuses/$COMMIT_ID
          echo "GITHUB_URL: $GITHUB_URL"
          echo "GITHUB_URL=$GITHUB_URL" >> $GITHUB_ENV
        if: always()

      - name: Upload screenshots for the 2nd project
        env:
          PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN2 }}
        id: upload_screenshots_2
        run: |
          build_output=$(npx smartui storybook ./storybook-static --config .smartui.json)
          echo "$build_output"
          build_id=$(echo "$build_output" | grep -oP '(?<=Build ID:  )\S+')
          echo "BUILD_ID_2=$build_id" >> $GITHUB_ENV
          echo "::set-output name=build_id_2::$build_id"
        continue-on-error: true

      - name: Debug Build ID 2
        run: |
          echo "Build ID: ${{ steps.upload_screenshots_2.outputs.build_id_2 }}"
          echo "Environment Build ID: $BUILD_ID_2"

      - name: Run API call with Build ID for 1st project
        env:
          BUILD_ID: ${{ steps.upload_screenshots.outputs.build_id }}
          PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
          API_AUTH: ${{ secrets.API_AUTH }}
        run: |
          echo "Using Build ID: $BUILD_ID"
          echo "Using Project Token: $PROJECT_TOKEN"
          curl -X GET "https://api.lambdatest.com/automation/smart-ui/build/status?projectToken=${PROJECT_TOKEN}&buildId=$BUILD_ID" -H "accept: application/json" -H "Authorization: Basic $API_AUTH"
        if: always()

      - name: Run API call with Build ID for 2nd project
        env:
          BUILD_ID: ${{ steps.upload_screenshots_2.outputs.build_id_2 }}
          PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN2 }}
          API_AUTH: ${{ secrets.API_AUTH }}
        run: |
          echo "Using Build ID: $BUILD_ID"
          echo "Using Project Token: $PROJECT_TOKEN"
          curl -X GET "https://api.lambdatest.com/automation/smart-ui/build/status?projectToken=${PROJECT_TOKEN}&buildId=$BUILD_ID" -H "accept: application/json" -H "Authorization: Basic $API_AUTH"
        if: always()
